# Example configuration for a four-peer system. 
Peers:
  0:
    IP: 127.0.0.1
    Port: 50000
  1:
    IP: 127.0.0.1
    Port: 50000
  2:
    IP: 127.0.0.1
    Port: 50000
  3:
    IP: 127.0.0.1
    Port: 50000
